In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Cleaned data.csv")

In [3]:
df.head()

,Unnamed: 0,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,...,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,0,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,...,1640.0,NaN,NaN,0,0,0,1,0,0,67
1,1,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,2.78,11346.0,2450.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,...,2690.0,2599.0,2450.0,1,1,0,0,0,0,174
2,2,3 BHK Flat in Sector 76 Gurgaon,flat,whiteland the aspen,sector 76,3.50,11917.0,2937.0,Built Up area: 2937 (272.86 sq.m.)Carpet area:...,3,...,NaN,2937.0,1762.0,0,0,0,0,0,0,0
3,3,3 BHK Flat in Sector 43 Gurgaon,flat,sanskriti apartments,sector 43,2.50,13513.0,1850.0,Super Built up area 1850(171.87 sq.m.),3,...,1850.0,NaN,NaN,1,0,0,0,0,0,0
4,4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,1.42,8998.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,...,1578.0,NaN,NaN,0,0,0,1,0,2,94

In [4]:
df['price_per_sqft']

0        6524.0
1       11346.0
2       11917.0
3       13513.0
4        8998.0
         ...
3663     8376.0
3664     7220.0
3665     8509.0
3666     8432.0
3667    11423.0
Name: price_per_sqft, Length: 3668, dtype: float64

In [6]:
df[(df['area'] < 250 ) & (df['bedRoom'] > 1)]

,Unnamed: 0,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,...,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
1586,1640,2 Bedroom House for sale in Garhi Harsaru,house,independent,sector 17,0.32,22068.0,145.0,Built Up area: 145 (13.47 sq.m.),2,...,NaN,145.0,NaN,0,0,0,0,0,0,0
2295,2387,2 Bedroom House for sale in Baldev Nagar,house,independent,sector 7,0.27,12000.0,225.0,Plot area 225(20.9 sq.m.),2,...,NaN,225.0,NaN,0,0,0,0,0,0,12

In [9]:
df['area'] / df['bedRoom']

0       820.000000
1       816.666667
2       979.000000
3       616.666667
4       526.000000
           ...
3663    636.666667
3664    692.500000
3665    615.000000
3666    504.000000
3667    604.000000
Length: 3668, dtype: float64

In [12]:
df[df['area'] < 500]

,Unnamed: 0,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,...,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
8,9,2 BHK Flat in Sector 99A Gurgaon,flat,conscient habitat,sector 99a,0.27,5599.0,482.0,Carpet area: 484 (44.97 sq.m.),2,...,NaN,NaN,484.00,0,0,0,0,1,0,49
23,24,7 Bedroom House for sale in Ashok Vihar Phase ...,house,ashok vihar phase iii extension,sector 3 phase 3 extension,0.40,8889.0,450.0,Plot area 50(41.81 sq.m.),7,...,NaN,450.0,NaN,0,0,0,1,0,0,7
24,26,1 BHK Flat in Sohna,flat,breez global heights,sohna road,0.25,7002.0,357.0,Super Built up area 414(38.46 sq.m.)Carpet are...,1,...,414.0,NaN,357.00,0,0,0,0,0,0,57
54,58,2 BHK Flat in Sector 99A Gurgaon,flat,laxmi pareena,sector 99a,0.30,6666.0,450.0,Carpet area: 450 (41.81 sq.m.),2,...,NaN,NaN,450.00,0,0,0,0,0,0,0
65,69,5 Bedroom House for sale in New Colony,house,independent,sector 7,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,...,NaN,477.0,NaN,0,0,0,0,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3537,3669,2 BHK Flat in Sohna,flat,gls arawali homes,sohna road,0.30,6243.0,481.0,Super Built up area 567(52.68 sq.m.)Carpet are...,2,...,567.0,NaN,480.53,0,0,0,0,0,1,120
3545,3677,2 BHK Flat in Sohna,flat,gls arawali homes,sohna road,0.28,5982.0,468.0,Carpet area: 468 (43.48 sq.m.),2,...,NaN,NaN,468.00,0,0,0,0,0,0,42
3590,3723,1 BHK Flat in Sector 92 Gurgaon,flat,gls avenue 51,sector 92,0.21,6953.0,302.0,Carpet area: 302 (28.06 sq.m.),1,...,NaN,NaN,302.00,0,0,0,0,0,0,63
3609,3742,2 BHK Flat in Sector 84 Gurgaon,flat,pivotal devaan,sector 84,0.35,7246.0,483.0,Carpet area: 483 (44.87 sq.m.),2,...,NaN,NaN,483.00,0,0,0,0,0,0,37
3630,3763,1 BHK Flat in Sohna,flat,breez global heights,sohna road,0.28,7142.0,392.0,Carpet area: 399 (37.07 sq.m.),1,...,NaN,NaN,399.00,0,0,0,0,0,1,26

In [ ]:
df=df[df['area'] > 500]